services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
    env_file: .env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - mailpanel_net
    ports:
      - 3308:3306
    volumes:
      - mailpanel_storage:/var/lib/mysql
    container_name: mailpanel_db
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - HOST=db
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - DB=${DATABASE}
    env_file: .env
    networks:
      - mailpanel_net
    ports:
      - 8088:80
    container_name: mailpanel_web
networks:
  mailpanel_net:
volumes:
  mailpanel_storage: